name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - test
      - prod
      - main

jobs:
  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

   
      - name: Deploy to Dev environment
        run: echo "Deploying to Development environment jou..."
        # Add your Dev deployment commands here
        # Example: `npm run deploy-dev`

  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Deploy to Test environment
        run: echo "Deploying to Test environment..."
        # Add your Test deployment commands here
        # Example: `npm run deploy-test`

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: first approval
        uses: hmarr/auto-approve-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GHATOKEN }}
        env:
          approvers: |
            tanekemgangdubois

      - name: Deploy to Production environment
        run: echo "Deploying to Production environment..."
        # Add your Production deployment commands here
        # Example: `npm run deploy-prod`

